on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created
permissions:
  contents: read
  id-token: write
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: install
        run:  npm install
      - name: build
        run:  npm run build
      - name: test
        run:  npm run test
        env:
          ETHEREUM_MAINNET_RPC: ${{ secrets.ETHEREUM_MAINNET_RPC }}
      - name: lint
        run:  npm run lint
      - name: benchmark
        run:  npm run bench
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
